version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    ports:
      - 3000:3000

  consumer:
    build: 
      context: .
      dockerfile: Dockerfile-client
    depends_on:
      - server
