/* tslint:disable */
/* eslint-disable */
/**
 * Simple API
 * Sample API to use swagger to generate a SDK.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: georgeo.rocco@x-team.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

