package main

import (
	"net/http"
	"server/handler"

	_ "server/docs" // docs is generated by Swag CLI, you have to import it.

	"github.com/labstack/echo/v4"
	echoSwagger "github.com/swaggo/echo-swagger"
)

//	@title			Simple API
//	@version		1.0
//	@description	Sample API to use swagger to generate a SDK.
//	@termsOfService	http://swagger.io/terms/

//	@contact.name	API Support
//	@contact.email	georgeo.rocco@x-team.com

// @schemes		http
// @host		server:3000
// @BasePath	/api/v1
func main() {
	e := echo.New()

	e.GET("/", func(c echo.Context) error {
		return c.Redirect(http.StatusPermanentRedirect, "/swagger/")
	})

	api := e.Group("/api/v1", serverHeader)
	api.GET("/jobs", handler.GetJobs)

	e.GET("/swagger/*", echoSwagger.WrapHandler)
	e.Logger.Fatal(e.Start(":3000"))
}

func serverHeader(next echo.HandlerFunc) echo.HandlerFunc {
	return func(c echo.Context) error {
		c.Response().Header().Set("x-version", "API/v1.0")
		return next(c)
	}
}
